### ISSUE TITLE
Weekly Scrum - Feb 26

### ISSUE THREAD

**Issue by BrijPatel15** [jobinmatt/SYSC4806_MiniShopify#26]
For last week, I was able to set up all libraries and frameworks for the project to use. I was able to test the fact that the DB persists and make sure that all tables are available after the application is redeployed.

For this coming week, I will set up the API endpoints for the shop page, and work to create controllers to make sure that the page works. #19

**Comment by RJBansal** [comment]
Last week, I set up data access models and tested to check the db schema was as expected. 
This week I will be working on issue #11, to create search and shop endpoints

**Comment by jobinmatt** [comment]
As planned during the last week's scrum, I had set up Travis CI to work with the master branch of our project. I also setup a new [Heroku App](https://sysc4806-minishopify.herokuapp.com/) as planned.
This week, I will be working on creating an HTML page view for the Shop.

**Comment by ShounakA** [comment]
Late post:
But I integrated Vue.js #27  and helped debug some deployment issues. As well as mocked up some designs in [Figma](https://www.figma.com/file/oBi79kBDDk0Ia0fWFpSmfg/Mini-Shopify?node-id=9%3A61)
This week I will be implementing Login, Signup, and Landing Page in Vue.js.
