### ISSUE TITLE
Stop the infinite nesting of objects in return  

### ISSUE THREAD

**Issue by BrijPatel15** [jobinmatt/SYSC4806_MiniShopify#39]
When we return from the API we get an infinite loop of objects back. We need to either change our objects to make sure that doesn't happen or come up with an alternative. Here is an example: 

{
    "id": 1,
    "name": "newName",
    "description": "newDesc",
    "tags": [
        "tag5",
        "tag3"
    ],
    "owner": {
        "id": 1,
        "firstName": "testf",
        "lastName": "testl",
        "email": "test",
        "password": "test",
        "ownedShops": [
            {
                "id": 1,
                "name": "newName",
                "description": "newDesc",
                "tags": [
                    "tag5",
                    "tag3"
                ],
                "owner": {
                    "id": 1,
                    "firstName": "testf",
                    "lastName": "testl",
                    "email": "test",
                    "password": "test",
                    "ownedShops": [
                        {
                            "id": 1,
                            "name": "newName",
                            "description": "newDesc",
                            "tags": [
                                "tag5",
                                "tag3"
                            ],
                            "owner": {
                                "id": 1,
                                "firstName": "testf",
                                "lastName": "testl",
                                "email": "test",
                                "password": "test",
                                "ownedShops": [
                                    {
                                        "id": 1,
                                        "name": "newName",
                                        "description": "newDesc",
                                        "tags": [
                                            "tag5",
                                            "tag3"
                                        ],
                                        "owner": {
                                            "id": 1,
                                            "firstName": "testf",
                                            "lastName": "testl",
                                            "email": "test",
                                            "password": "test",
                                            "ownedShops": [
                                                {
                                                    "id": 1,
                                                    "name": "newName",
                                                    "description": "newDesc",
                                                    "tags": [
                                                        "tag5",
                                                        "tag3"
                                                    ],
                                                    "owner": {
                                                        "id": 1,
                                                        "firstName": "testf",
                                                        "lastName": "testl",
                                                        "email": "test",
                                                        "password": "test",
                                                        "ownedShops": [
                                                            {
                                                                "id": 1,
                                                                "name": "newName",
                                                                "description": "newDesc",
                                                                "tags": [
                                                                    "tag5",
                                                                    "tag3"
                                                                ],
                                                                "owner"

**Comment by ShounakA** [comment]
this is fixed right?
