### ISSUE TITLE
Weekly scrum - March 12

### ISSUE THREAD

**Issue by jobinmatt** [jobinmatt/SYSC4806_MiniShopify#62]
Last week, I created the create shop page and fixed issues with heroku hosting.
This week, I will make the create shop page function by linking with backend API endpoints.

**Comment by ShounakA** [comment]
Last week, I created the helped debug issues with heoku deployment, and wrote quick unit tests for frontend.
This week, will hook Login and Signup view to Spring controller .

**Comment by BrijPatel15** [comment]
Setup testing framework, had to wrestle with Mocking objects but now there are tests for all methods in the ShopController.

**Comment by RJBansal** [comment]
Worked on backend for logging. Working on search controller and unit tests for both
