### ISSUE TITLE
Weekly scrum - March 24

### ISSUE THREAD

**Issue by jobinmatt** [jobinmatt/SYSC4806_MiniShopify#84]

**Comment by jobinmatt** [comment]
Last week, I made the createChop functional.
This week I plan to add a userShops page -  a page that displays all shops that a user owns.
I also plan to add a page that allows a user to edit the the information about a store.

**Comment by BrijPatel15** [comment]
Last week I got the testing framework up and running and made tests for the ShopController endpoint. 
This week I have to make the endpoint for the search functionality, also fix the bug where delete isn't behaving as we want too for shop. Also I have to create missing tests for endpoints.

**Comment by ShounakA** [comment]
Last week, added JWT token user authentication, which allowed Login and Signup functionality. As well as making most endpoints private and needing authentication before requested.
This week, I helped fix some dependency issues with Junit, Mockito, allowing us to get tests working. Will try and finish some outstanding stories. Also working on a small client for demo.

**Comment by BrijPatel15** [comment]
Added tests and updated readMe. Helped with bug with add, remove cart items.
